### ISSUE TITLE
Identify Interactive Elements and Display

### ISSUE THREAD

**Issue by hemkan** [hemkan/MotorEase#4]
### Description
User Story: As a user, I should be able to see/know the feature that is considered an interactive element.

Currently, the number of interactive elements is shown. This number doesn't provide information about which elements they are. This issue focuses on identifying which interactive elements exist on the page.

### Ranking and Reasoning:
This is ranked 2nd because it focuses on a feature that could potentially hinder the usability of the tool. Knowing which elements are interactive is important for the user to map to them easily. Our ranking system is prioritized in the following way: errors > usability/function > UI. This would fall under usability/function as it enhances user experience and usability.

### Dependencies
There are no dependencies for this task

### Ideas for Fix
Go through the .xml file for a given screen and find elements/nodes that have clickable set to true. Find the location where the AccessibilityReport.txt is being made and display this snippet or specific information about the element that makes it easily identifiable without needing to browse through the .xml file.

### Timeline
Engineering Points/Effort: 2 points (2 day's worth of work). This bug fix should be completed by Sprint 1.

### Acceptance Criteria.
Interactive elements are labeled
All relevant information about an interactive element is shown in AccessibilityReport.txt
The shown interactive elements are accurate upon cross-checking from the .xml file
Testing will be done with the existing images containing known interactive elements to verify that they are being identified accurately.

**Comment by hemkan** [comment]
duplicate issue that doesn't show the flow in the kanban board

**Comment by anguyen644** [comment]
Oops accidentally edited this thinking it was the mock PR. I reverted the changes back to Hema's original but this was a draft issue that didn't make it through lol. Sorry again!
